mock:
  url: http://localhost:8080/mock

retry:
  maxAttempts: 3

feign:
  client:
    config:
      default: # Global confg
        connectTimeout: 2000
        readTimeout: 2000
        loggerLevel: BASIC
      client: # Per client
        connectTimeout: 3000
        readTimeout: 3000
        loggerLevel: FULL
